### PR TITLE
HTML review code

### PR DESCRIPTION
**Pull request by nicolasdanelon**
```
Remove slash from meta tags.
noscript tag inside of body element
Adding Oswald Google Fonts instead of Ostrich Bold
```
# Details of pull request
1. Meta tags, in HTML5, don't use a slash at the end any more.
2. noscript tag creates a div. The div must be inside of body element.
3. Ostrich Bold replaced by Oswald because Ostrich is not a web safe font.
4. Pipe symbol ( | ) is encode for HTML5 valitation

*TLDR part:*

## [Definition and Usage (noscript tag)](http://www.w3schools.com/tags/tag_noscript.asp)

The &lt;noscript&gt; tag defines an alternate content for users that have disabled scripts in their browser or have a browser that doesn't support script.
**The &lt;noscript&gt; element can be used in both &lt;head&gt; and &lt;body&gt;.**
When used inside the &lt;head&gt; element: &lt;noscript&gt; must contain &lt;link&gt;, &lt;style&gt;, and &lt;meta&gt; elements.
The content inside the &lt;noscript&gt; element will be displayed if scripts are not supported, or are disabled in the user's browser.

## [Definition and Usage (meta tag)](http://www.w3schools.com/tags/tag_meta.asp)

Metadata is data (information) about data.
The &lt;meta&gt; tag provides metadata about the HTML document. Metadata will not be displayed on the page, but will be machine parsable.
Meta elements are typically used to specify page description, keywords, author of the document, last modified, and other metadata.
The metadata can be used by browsers (how to display content or reload page), search engines (keywords), or other web services.

### Examples

Example 1 - Define keywords for search engines:
```html
<meta name="keywords" content="HTML, CSS, XML, XHTML, JavaScript">
```
Example 2 - Define a description of your web page:
```html
<meta name="description" content="Free Web tutorials on HTML and CSS">
```
Example 3 - Define the author of a page:
```html
<meta name="author" content="Hege Refsnes">
```
Example 4 - Refresh document every 30 seconds:
```html
<meta http-equiv="refresh" content="30">
```

##### More info
- http://www.w3.org/wiki/HTML/Elements/noscript
- http://www.w3.org/wiki/HTML/Elements/meta
- http://www.w3.org/TR/html5/document-metadata.html
- http://www.w3.org/TR/html401/struct/global.html#h-7.4.4

### CODE REVIEW

**Comment by snwh** [comment]
I would like to merge this, but this isn't the true source of the site. This repo is simply the public open source version the site, that is the build output.

**Comment by nicolasdanelon** [comment]
If you need help.. I can do that :)

**Comment by snwh** [comment]
It's already done. ;)

**Comment by nicolasdanelon** [comment]
### Please check the css file, and the request to Google Fonts :)

###### this is my pull request
screenshot from 2015-02-23 11 53 13

###### this is the current website
screenshot from 2015-02-23 11 53 11

## svg issues

captura de pantalla de 2015-02-23 15 14 15
captura de pantalla de 2015-02-23 15 13 55

**Pull request closed without merging**
